[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
screen_wars = "4jqrWDfeR2RAzSPYNoiVq2dcVrZUrsp3ZWEPHehVwCtW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com" #"http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json" #"../../wallets/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
