[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "3MZi8MF8xzf7JusYnsUgW3Dia3qNgG1n7jE1Hm19svMi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "../wallets/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
